### ISSUE TITLE
The use of high-pressure steering servo 8.4v

### ISSUE THREAD

**Issue by tonight123** [SpektreWorks/spektreworks.github.io#4]
The use of high-pressure steering servo 8.4v, servo access main1, main2, main4, 2s lipo battery access main1, then the remaining ports will have 8.4v power, does not affect the esc use esc only s and gnd

**Comment by DavidIngraham** [comment]
Hello @tonight123,

Yes, it is ok to connect a 2S Lipo to the main servo rail. However, make sure that you have not bridged the solder jumper JP1.

Does this answer your question?
