### ISSUE TITLE
U106 Component

### ISSUE THREAD

**Issue by AsternA** [SpektreWorks/spektreworks.github.io#5]
Hey Guys, 

I am confident that i have burned out a single component (909xz OR zx606) connected in slot U106. 
Is it possible to know what i have burned? (Coil, Capacitor, other?), its value and the consequences?

Thanks!

Almog

**Comment by SpektreWorks** [comment]
Hi Almog,

U106 is a logic gate (an XOR gate, part number 74AHCT1G86SE-7) that controls the red error LED. It is not critical for flight, but it provides a useful visual indication that one of the on-board power supplies has failed. If it shows signs of damage, I would not recommend flying. It may have shorted across one of the power supplies.

We have had some problems with that particular part before. If you'd like to send the board to us, we will replace it at no charge.

-Dan

**Comment by AsternA** [comment]
Great!!

Will begin to work out how to send it you tomorrow!

Almog
